#!/bin/bash
# enable color support of ls and also add handy aliases
# if [ -x /usr/bin/dircolors ]; then
# test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
alias ls='ls --color=auto'
#alias dir='dir --color=auto'
#alias vdir='vdir --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
# fi

# colored GCC warnings and errors
#export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'
# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'
# some more ls aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias lss='ls | less'

#--------------------------------------------------------------------------
# OWN ALIASES
#--------------------------------------------------------------------------

alias "vim"="stty stop '' -ixoff ; nvim"
alias "tmux"="stty stop '' -ixoff ; tmux"

if [[ "$TERM" == "xterm-kitty" ]]; then
  alias 'diff'='kitten diff'
fi

#cd
alias '..'='cd ..'
alias '...'='cd ..;ls'

alias 'pip_update_all'='pip list --outdated --format=freeze | cut -d = -f 1 | xargs -n1 sudo  pip install -U'
alias 'pip_update_all'='pip list --outdated --format=freeze | cut -d = -f 1 > pip.packages'
alias 'pip3'='python3.12 -m pip install --upgrade --break-system-packages'

# open neovimrc in neovim
alias 'vimrc'='cd ~/.config/nvim/ && vim .'
# alias 'yank'='yank-cli -- xsel -b' 
alias 'ovito'='/Applications/Ovito.app/Contents/MacOS/ovito'
export PATH=".cargo/bin:$PATH"

#ranger exits at its last location
alias ranger='ranger --choosedir=$HOME/.rangerdir; LASTDIR=`cat $HOME/.rangerdir`; cd "$LASTDIR"'

# reload zshrc
alias 'rerc'='source ~/.zshrc'

# change OS color theme
function poke_kitty_color {
  # kitty @ set-colors -a -c ~/.config/kitty/current-theme.conf
  bash ~/dotfiles/config/kitty/i_theme-switcher.sh || bash ~/dotfiles/config/kitty/theme-switcher.sh
}
function toggle_system_color {
  osascript -e 'tell app "System Events" to tell appearance preferences to set dark mode to not dark mode'
}

alias  'revolve'='toggle_system_color && poke_kitty_color'

# project patterns
PROJPAT='^[a-z]\?p\d\?.*'
alias list_projects='ls |  grep "${PROJPAT}"'

alias 'slimekitty'='kitty -o allow_remote_control=yes --listen-on unix:/tmp/mykitty 1> /dev/null 2> /dev/null'

export MODULAR_HOME="$HOME/.modular"
export PATH="$MODULAR_HOME/pkg/packages.modular.com_mojo/bin:$PATH"




# TMUX setup
alias tn="tmux new -s $(pwd | sed 's/.*\///g')"
alias "chtsh"="~/dotfiles/cht.sh"
# /TMUX  setup
