#!/bin/bash

# colored GCC warnings and errors
export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'

# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
alias alert='notify-send --urgency=critical -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

#--------------------------------------------------------------------------
# modern versions
#--------------------------------------------------------------------------
alias ls='eza'
alias ll='eza -alF'
alias la='eza -A'

alias cat='bat'

#--------------------------------------------------------------------------
# OWN ALIASES
#--------------------------------------------------------------------------

alias "vim"="stty stop '' -ixoff ; nvim"
alias "manvim"="nvim +Man!"
alias "tmux"="stty stop '' -ixoff ; tmux"

# open neovimrc in neovim
alias 'vimrc'='cd ~/dotfiles/config/nvim/ && vim .'
alias 'rebind'='bash ~/dotfiles/gnome_custom_hotkeys.sh'

# reload zshrc
alias 'rerc'='source ~/.zshrc'

export PATH=$PATH:~/.local/bin/

