#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$(find ~/Documents/Side_Projects ~/Documents/my_github_projects ~/Documents/LMU ~/Documents/guga ~/Documents/TUD ~/Documents ~/.config ~/dotfiles/ ~/dotfiles/config/ ~/dotfiles/config/kitty ~/dotfiles/config/nvim/ ~/.config -mindepth 1 -maxdepth 4 -type d | fzf)
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

echo tmux_running: "$tmux_running"

if [[ -z $tmux_running ]]; then
  echo "Starting tmux" "$selected_name" "$selected"
    tmux new-session -s "$selected_name" -c "$selected"
    exit 0
fi

if ! tmux has-session -t="$selected_name" 2> /dev/null; then
    tmux new-session -ds "$selected_name" -c "$selected"
fi


if [[ -z $TMUX ]]; then
  tmux new-session -t "$selected_name"
fi

tmux switch-client -t "$selected_name"
